### ISSUE TITLE
애니메이션 구현하기

### ISSUE THREAD

**Issue by AnSuebin** [suno0140/FE-CloneCode#13]
## Description
메인페이지, 상품 리스트 페이지 애니메이션을 animation function으로 만들어 구현해보기 

## Todo
- [ ] 헤더 내리면, 형태 변환 구현
- [ ] 카테고리에 올렸을 때, 세부 카테고리 나오도록 구현
- [ ] 메인 캐러셀 구현
- [ ] 메인, 상품 리스트 페이지 상품 처음 보여줄 때, 위로 띄우는 애니메이션 구현

## Etc
기타사항
